config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post 'guest_login' => 'sessions#guest_login'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity', to: 'carts#change_quantity', as: 'change_item_quantity'
  delete 'carts/destroy_carts_item', to: 'carts#destroy_carts_item', as: 'destroy_carts_item'
  get '/perchase_completed/:id', to: 'orders#perchase_completed', as: 'perchase_completed'
  resources :products
  resources :users
  resources :orders
  root to: 'static_pages#home'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy

  def shipment_prepared?
    order_details.any? do |order_detail|
      order_detail.shipment_status.shipment_status_name == "準備中"
    end
  end

  def total_price
    order_details.sum(&:sub_total_price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :correct_users_order, only: [:show]

  def index
    @orders = current_user.orders.page(params[:page]).per(15)
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  #### TODO:カートに商品が入ってる状態で当該商品を消し、カートに入っている商品すべて存在しないものにしてから注文ボタンを押すした際に中身のないOrderが作成されることを防ぐ ####
  # カート内商品情報を保存する
  def create
    if session[:cart].blank?
      return redirect_to carts_show_path
    end

    complex_data = "#{current_user.id}#{Time.current.to_i}"
    order = current_user.orders.create!(
      order_date: Time.current,
      order_number: complex_data.rjust(16, "0"),
    )
    session[:cart].each do |cart|
      order.order_details.create(
        product_id: cart["product_id"],
        shipment_status_id: 1,
        order_detail_number: "#{cart["product_id"]}#{complex_data}".rjust(16, "0"),
        order_quantity: cart["quantity"],
      )
    end
    session[:cart].clear
    redirect_to perchase_completed_path(order.id)
  end

  def perchase_completed
    @display_number = Order.find_by(id: params[:id]).order_number
  end

  def correct_users_order
    unless current_user.id == Order.find(params[:id]).user_id
      flash[:danger] = "他人の情報にアクセスすることはできません。"
      redirect_to root_path
    end
  end

  def destroy
    current_user.orders.find(params[:id]).destroy!
    flash[:success] = "注文がキャンセルされました。"
    #### TODO: 注文履歴のページが作成されたらリダイレクト先に注文履歴ページのパスを指定する ####
    redirect_to root_path
  end
end

app/views/orders/index.html.erb
<main>
  <div class="container">
    <% if @orders %>
      <table class="table mt-5">
        <thead class="table-sm h4">
          <tr>
            <th class="text-left" width="5%">No</th>
            <th class="text-left" width="20%">注文番号</th>
            <th class="text-left" width="40%">お届け先</th>
            <th class="text-left" width="25%">備考</th>
            <th class="text-left border-0" width="20%"></th>
          </tr>
        </thead>
        <tbody class="h6 font-weight-normal">
          <% @orders.each.with_index(1) do |order, i| %>
            <tr>
              <th scope="row" class="font-weight-normal"><%= i %></th>
              <td class="text-left"><%= order.order_number %></td>
              <td class="text-left">
                〒<%= order.user.zipcode %><br>
                <%= order.user.prefecture %> <%= order.user.municipality %> <%= order.user.address %><br>
                <%= order.user.last_name %> <%= order.user.first_name %> 様
              </td>
              <td class="text-left">
                <%= order.order_date %><br>
                <p>注文状態：
                  <% if order.shipment_prepared? %>
                    準備中
                  <% else %>
                    発送済
                  <% end %>
                </p>
              </td>
              <td class="border-0 align-middle">
                <%= link_to "詳細", order_path(order.id), class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="container">
        <%= paginate @orders %>
      </div>
    <% else %>
      <div class="not-find-box mt-5" style="text-align: center;">
        <div class="nf-message">注文履歴は存在しません</div>
      </div>
    <% end %>
  </div>
</main>

app/views/orders/perchase_completed.html.erb
<main>
  <div class="blockquote mt-5 text-center">
    <h1 style="font-weight: bolder">購入完了しました</h1>
  </div>
  <div class="container-sm mt-5 text-center">
    <p class="h1">ご購入ありがとうございます！</p>
    <p class="h1">
    <%= @display_number %>
    </p>
  </div>
  <div class="container text-center mt-5">
    <%= link_to "Topに戻る", root_path, class: "btn btn-primary mt-5" %>
  </div>
</main>

app/views/orders/show.html.erb
<main>
  <div class="container">
    <div class="jumbotron bg-white">
      <% if @order %>
        <div class="card border-dark mt-3">
          <div class="cord-body px-3 ml-3">
            <h4 class="mt-4">お届け先</h4>
            <p class="ml-3">〒<%= @order.user.zipcode%>　<%= @order.user.prefecture %> <%= @order.user.municipality %> <%= @order.user.address %></p>
            <p class="offset-sm-2"><%= @order.user.last_name %> <%= @order.user.first_name %> 様</p>
          </div>
        </div>
        <div class="mt-5 ml-3">
          <p>注文番号： <%= @order.order_number %></p>
          <p>注文状態：
            <% if @order.shipment_prepared? %>
              準備中
            <% else %>
              発送済
            <% end %>
          </p>
        </div>
        <% if @order.shipment_prepared? %>
          <div class="text-right">
            <%= link_to "注文をキャンセルする", order_path, method: :delete, class: "btn btn-danger", data: {confirm: "注文をキャンセルしてもよろしいですか？"}%>
          </div>
        <% end %>
        <table class="table table-borderless mt-3">
          <thead>
            <tr>
              <th scope="col" class="border-top border-bottom">No</th>
              <th scope="col" class="border-top border-bottom">商品名</th>
              <th scope="col" class="border-top border-bottom">商品カテゴリ</th>
              <th scope="col" class="border-top border-bottom">値段</th>
              <th scope="col" class="border-top border-bottom">個数</th>
              <th scope="col" class="border-top border-bottom">小計</th>
              <th scope="col" class="border-top border-bottom">備考</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_details.each.with_index(1) do |order_detail, i| %>
              <tr>
                <th scope="row"><%= i %></th>
                <td><%= order_detail.product.product_name %></td>
                <td><%= order_detail.product.category.category_name %></td>
                <td><%= order_detail.product.price %></td>
                <td><%= order_detail.order_quantity %> 個</td>
                <td><%= order_detail.sub_total_price %> 円</td>
                <td>注文状態：<%= order_detail.shipment_status.shipment_status_name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="border-top border-dark">
          <div  class="mt-2 offset-sm-6">
            <p class="ml-4">合計　　　　　<%= @order.total_price %> 円</p>
          </div>
        </div>
        <div class="text-right mb-5">
          <button type="button" class="btn btn-info">注文履歴に戻る</button>
        </div>
      <% else %>
        <div class="text-center">
          <h1>該当の注文は見つかりませんでした…</h1>
          <p class="mt-5">注文履歴画面に戻り、やり直してください</p>
          <button type="button" class="btn btn-primary">注文履歴へ</button>
        </div>
      <% end %>
    </div>
  </div>
</main>