config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post 'guest_login' => 'sessions#guest_login'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity', to: 'carts#change_quantity', as: 'change_item_quantity'
  delete 'carts/destroy_carts_item', to: 'carts#destroy_carts_item', as: 'destroy_carts_item'
  get '/perchase_completed/:id', to: 'orders#perchase_completed', as: 'perchase_completed'
  resources :products
  resources :users
  resources :orders
  root to: 'static_pages#home'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    return if session[:cart].blank?

    @cart = []
    session[:cart].each do |cart|
      product = Product.find_by(id: cart["product_id"])
      sub_total = product.price * cart["quantity"].to_i
      next unless product

      @cart.push({ product_id: product.id,
                   name: product.product_name,
                   category_name: product.category.category_name,
                   price: product.price,
                   quantity: cart["quantity"].to_i,
                   sub_total: sub_total })
    end
    @cart_total_price = cart_total_price(@cart)
  end

  def add_cart
    # 個数が0このまま入力されている商品を弾く。
    if session[:cart].blank?
      if params["quantity"].blank?
        flash[:danger] = "商品をカートに追加できませんでした。個数を入力してください"
        return redirect_to product_path(id: params[:product_id])
      end
      # session内の商品の有無で条件分岐
      # 商品が入っていない場合
      session[:cart] = [{ product_id: params["product_id"], quantity: params["quantity"].to_i }]
      return redirect_to carts_show_path
    end
    # 商品が既に入っている場合、追加する商品が重複するかで条件分岐
    match = session[:cart].select {|cart| cart["product_id"] == params["product_id"] }
    # 重複が発生する場合
    if match.present?
      match[0]["quantity"] += params["quantity"].to_i
    # 重複が発生しない場合
    else
      session[:cart].push({ product_id: params["product_id"], quantity: params["quantity"].to_i })
    end
    redirect_to carts_show_path
  end

  # カート内商品の数量変更
  def change_quantity
    array_index = session[:cart].each_index.select {|i| session[:cart][i]["product_id"] == params["product_id"] }
    session[:cart][array_index[0]]["quantity"] = params["quantity"]
    redirect_to carts_show_path
  end

  # カート内商品の削除
  def destroy_carts_item
    array_index = session[:cart].each_index.select {|i| session[:cart][i]["product_id"] == params["product_id"] }
    session[:cart].delete_at(array_index[0])
    redirect_to carts_show_path
  end

  # カート内商品の合計金額の計算
  def cart_total_price(cart)
    cart.sum { _1[:sub_total] }
  end
end

app/views/carts/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-12 card border-dark mt-5">
        <div class="cord-body ml-3 mb-2">
          <h4 class="mt-4">お届け先</h4>
          <p class="mb-2" style="padding-left: 20px;">
            〒
            <%= current_user.zipcode %>
            <%=  current_user.prefecture %>
            <%=  current_user.municipality %>
            <%=  current_user.address %>
            <%=  current_user.apartments %>
          </p>
          <p style="padding-left: 160px;">
            <%=  current_user.last_name %>
            <%=  current_user.first_name %>
            様
          </p>
        </div>
      </div>
    </div>
  </div>
  <% if @cart.blank? %>
    <h1 class="text-center">カートに商品はありません</h1>
  <% else %>
    <div class="container">
      <div class="row">
        <table class="table mt-5 ml-3 border-dark">
          <thead>
            <tr class="text-center">
              <th class="border-bottom border-dark" style="width:13%;">
                No
              </th>
              <th class="border-bottom border-dark" style="width:18%;">
                商品名
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                商品カテゴリ
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                値段
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                個数
              </th>
              <th class="border-bottom border-dark" style="width:15%;">
                小計
              </th>
            </tr>
          </thead>
          <tbody>
            <% @cart.each.with_index(1) do |cart, i| %>
            <tr class="text-center">
              <th class="align-middle">
                <%= i %>
              </th>
              <td class="align-middle">
                <%= cart[:name] %>
              </td>
              <td class="align-middle">
                <%= cart[:category_name] %>
              </td>
              <td class="align-middle">
                <%= cart[:price] %> 円
              </td>
              <% #数量変更 %>
              <%= form_with url: change_item_quantity_path, method: :patch, local: true do |f| %>
              <td class="align-middle">
                <%= f.number_field :quantity, value: cart[:quantity], min: 1, class: "btn btn-outline-dark"%> 個
              </td>
              <td class="align-middle">
                <%= cart[:sub_total] %> 円
              </td>
              <td>
                <%= hidden_field_tag :product_id, cart[:product_id] %>
                <%= f.submit "更新", class: "btn btn-primary" %>
              </td>
              <% end %>
              <% #商品削除 %>
              <%= form_with url: destroy_carts_item_path, method: :delete, local: true do |f| %>
              <td class="border-0 align-middle">
                <%= hidden_field_tag :product_id, cart[:product_id] %>
                <%= f.submit "削除", class: "btn btn-danger" %>
              </td>
              <% end %>
            </tr>
            <% end %>
            <tr class="text-center">
              <td class="border-bottom-0 align-right"></td>
              <td class="border-bottom-0 align-right"></td>
              <td class="border-bottom-0 align-right"></td>
              <td class="border-bottom-0 align-right"></td>
              <td class="border-bottom-0 align-right">
                合計
              </td>
              <td class="border-bottom-0 align-right">
                <%= @cart_total_price %>円
              </td>
            </tr>
            <tr class="text-right">
              <th class="border-0">
              </th>
              <td class="border-0">
                <%= link_to "買い物を続ける", products_path, class: "btn btn-success"%>
              </td>
              <td class="border-0">
              </td>
              <td class="border-0">
              </td>
              <td class="border-0">
                <%= link_to "注文を確定する", orders_path, method: :post,  class: "btn btn-primary"%>
              </td>
              <td class="border-0 align-middle">
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</main>