config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post 'guest_login' => 'sessions#guest_login'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity', to: 'carts#change_quantity', as: 'change_item_quantity'
  delete 'carts/destroy_carts_item', to: 'carts#destroy_carts_item', as: 'destroy_carts_item'
  get '/perchase_completed/:id', to: 'orders#perchase_completed', as: 'perchase_completed'
  resources :products
  resources :users
  resources :orders
  root to: 'static_pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :purchases, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :sale_status
  belongs_to :product_status

  def self.search(keyword, category_id)
    products = Product.all

    if keyword.present?
      products = products.where(["product_name LIKE ?", "%#{keyword}%"])
    end

    if category_id.present?
      products = products.where(category_id: category_id)
    end

    products   # return products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes([:category]).search(params[:keyword], params[:category_id]).page(params[:page]).per(15)
  end

  def show
    @product = Product.find_by(id: params[:id])
  end
end

app/views/products/index.html.erb
<main>
  <div class="mt-5 mx-auto" style="width: 200px">
    <h2>商品検索画面</h2>
  </div>

  <%= form_with url: products_path, method: :get, local: true do |form| %>
    <div class="container mt-5">
      <div class="mx-auto row">
        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">商品名</label>
        <div class="col-sm-6">
          <%= form.text_field :keyword, class: "form-control form-control-lg", id: "colFormLabelLg", value: "#{params[:keyword]}" %>
        </div>
        <div class="col-sm-4 mt-1">
          <%= form.submit '検索', :name => nil, class: "btn btn-primary", style: "width: 80px" %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="mx-auto row">
        <label class="col-sm-2 col-form-label col-form-label-lg" for="exampleFormControlSelect2">商品カテゴリ</label>
        <div class="col-sm-4">
          <%= form.collection_select :category_id, Category.all, :id, :category_name, include_blank: "未選択", selected: "#{params[:category_id]}" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <p>全<%= @products.count %>件</p>
    <table class="table table-hover" border="1" style="border-collapse: collapse">
      <thead>
        <tr class=" table-header">
          <th class="text-left" width="55%">
            商品名
          </th>
          <th class="text-center" width="15%">
            商品カテゴリ
          </th>
          <th class="text-center" width="15%">
            価格
          </th>
          <th class="text-center" width="15%"></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td scope="row">
              <%= product.product_name %>
            </td>
            <td class="text-center">
              <%= product.category.category_name %>
            </td>
            <td class="text-center">
              <%= product.price %>
            </td>
            <td class="text-center">
              <%= link_to "商品詳細", "/products/#{product.id}", class: "btn btn-primary btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  

  <%= paginate @products %>

</main>

app/views/products/show.html.erb
<main>
  <% if @product %>
    <section>
      <div class="product-detail">
        <div class="product-infomation">
          <h2 class="info">商品情報</h2>
          <div class="name"><%= @product.product_name %></div>
          <div class="category">カテゴリ: <%= @product.category.category_name %></div>
        </div>
        <div class="product-description">
          <div class="desc">商品説明</div>
          <div class="desc-body"><%= @product.description %></div>
        </div>
        <div class="product-price">
          <div class="price">価格 : <span><%= @product.price %>円</span></div>
        </div>
          <%= form_with url: carts_add_cart_path, method: :post, local: true do |f| %>
            <%= f.label :quantity, "購入個数", class: "pur-number-box"%>>
            <%= f.number_field :quantity, min: 1, class: "pur-number" %>>
            <%= hidden_field_tag :product_id, @product.id %>
            <%= f.submit "カートへ", class: "cart-button" %>>
          <% end %>
      </div>
    </section>
  <% else %>
    <section>
      <div class="not-find-box" style="text-align: center;">
        <div class="nf-message">該当商品が見つかりませんでした…</div>
        <div class="nf-sub-message">商品検索画面に戻り、やり直してください</div>
        <%= link_to "商品検索画面", products_path, class: "product-search-button" %>
      </div>
    </section>
  <% end %>
</main>