config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post 'guest_login' => 'sessions#guest_login'
  get 'carts/show', to: 'carts#show', as: 'carts_show'
  post 'carts/add_cart', to: 'carts#add_cart'
  patch 'carts/change_quantity', to: 'carts#change_quantity', as: 'change_item_quantity'
  delete 'carts/destroy_carts_item', to: 'carts#destroy_carts_item', as: 'destroy_carts_item'
  get '/perchase_completed/:id', to: 'orders#perchase_completed', as: 'perchase_completed'
  resources :products
  resources :users
  resources :orders
  root to: 'static_pages#home'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notification alert alert-<%= key %>">
    <p class="<%= key %>"><%= value %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <h1>探求学園Rails専攻</h1>
  <p>© 2020 QuestAcademia, All rights reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <div class="navbar-nav mr-auto">
        <h1><%= link_to "探求学園Rails専攻", root_path, class: "nav-link navbar-brand"%></h1>
      </div>
      <div>
        <div class user_icon>
          <ul>
            <% if logged_in? %>
            <p><%= current_user.last_name %> <%= current_user.first_name %> さん </p>
            <% if current_user.image? %>
            <%= image_tag current_user.image.thumb.url %>
            <% end %>
            <% end %>
        </div>
        </ul>
        <ul class="navbar-nav">
          <% if logged_in? %>
          <%= link_to "商品検索", products_path, class: "nav-link text-dark"%>
          <%= link_to "カート", carts_show_path, class: "nav-link text-dark"%>
          <%= link_to "注文履歴", orders_path, class: "nav-link text-dark"%>
          <%= link_to "ユーザ情報", user_path(current_user.id), class: "nav-link text-dark"%>
          <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link text-dark" %>
          <% else %>
          <%= link_to "新規登録", signup_path, class: "nav-link text-dark" %>
          <%= link_to "ログイン", login_path, class: "nav-link text-dark" %>
          <%= link_to 'ゲストログイン', guest_login_path, method: :post, class: "nav-link text-dark" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>探求学園Rails専攻</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/flash_messages' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>